# In the future, when APIcast provide a standard way to install modules this
# Dockerfile might not be needed.
FROM quay.io/3scale/apicast:v3.0.0

USER root

# Install everything we need to install XC depencies using luarocks
RUN yum install -y epel-release \
 && yum upgrade -y \
 && yum install -y lua-devel make gcc wget unzip epel-release luarocks \
 && yum clean all -y

# Looks like this is necessary in some Apicast versions.
# Remove this line when Apicast images are fixed.
RUN rm -rf /opt/app-root/src/logs

USER default

# Copy XC source code to the appropriate directory
COPY apicast_xc.lua apicast_xc.rockspec Makefile /opt/app-root/src/src/
COPY xc /opt/app-root/src/src/xc

# Install XC dependencies
WORKDIR /opt/app-root/src/src/
RUN make apicast.xc

WORKDIR /opt/app-root
